{% set name = "pdbinf" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdbinf-{{ version }}.tar.gz
  sha256: 5d98288961664f8ac87eabd76bcdb33c7dad3ed3f54a4d2347fb86258595322c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - rdkit
    - gemmi
    - numpy

test:
  imports:
    - pdbinf

about:
  home: https://github.com/OpenFreeEnergy/pdbinf
  summary: Load PDB files into rdkit with nonstandard residues
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richardjgowers
    - dwhswenson
    - mikemhenry
    - IAlibay
    - RiesBen
