{% set name = "pdbinf" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - rdkit
    - gemmi
    - numpy

test:
  imports:
    - pdbinf

about:
  home: https://github.com/OpenFreeEnergy/pdbinf
  summary: Load PDB files into rdkit with nonstandard residues
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richardjgowers
    - dwhswenson
    - mikemhenry
    - IAlibay
    - RiesBen
